### ISSUE TITLE
Error with latest client & p2pool

### ISSUE THREAD

**Issue by p3yot3** [domob1812/i0coin#1]
2015-11-09 13:48:20.429566 > Error while calling merged getauxblock on http://127.0.0.1:7338/:
2015-11-09 13:48:20.429667 > Traceback (most recent call last):
2015-11-09 13:48:20.429696 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
2015-11-09 13:48:20.429735 >     current.result = callback(current.result, _args, *_kw)
2015-11-09 13:48:20.429762 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155, in gotResult
2015-11-09 13:48:20.429787 >     _inlineCallbacks(r, g, deferred)
2015-11-09 13:48:20.429823 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2015-11-09 13:48:20.429857 >     result = result.throwExceptionIntoGenerator(g)
2015-11-09 13:48:20.429886 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-11-09 13:48:20.429931 >     return g.throw(self.type, self.value, self.tb)
2015-11-09 13:48:20.429966 > --- <exception caught here> ---
2015-11-09 13:48:20.430017 >   File "/home/rig/p2pool/p2pool/util/deferral.py", line 41, in f
2015-11-09 13:48:20.430057 >     result = yield func(_args, *_kwargs)
2015-11-09 13:48:20.430088 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2015-11-09 13:48:20.430119 >     result = result.throwExceptionIntoGenerator(g)
2015-11-09 13:48:20.430149 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-11-09 13:48:20.430180 >     return g.throw(self.type, self.value, self.tb)
2015-11-09 13:48:20.430226 >   File "/home/rig/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
2015-11-09 13:48:20.430258 >     raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
2015-11-09 13:48:20.430296 > p2pool.util.jsonrpc.NarrowError: -12 Error: Keypool ran out, please call keypoolrefill first

This is running on Xubuntu 64bit. Previous version ran fine.

**Comment by domob1812** [comment]
Judging from the final message, your keypool ran out. :)  Please use `keypoolrefill` or unlock the wallet to recreate new keys.  Unlike some previous versions, the current one does not reuse addresses for mining.  This is the same in upstream Bitcoin.

**Comment by p3yot3** [comment]
Right, sorry - news to me. Is it a case of starting i0coind with the -keypoolrefill command or can I enter it via ssh when the wallet is running?

Sorry for my ignorance - never came across this before......

**Comment by domob1812** [comment]
No problem!  I don't have experience with the option, but it should suffice to issue `i0coin-cli keypoolrefill SOMELARGENUMBER` via SSH (unlock the wallet first, of course).  Also, very important, make sure to create a fresh backup afterwards!

**Comment by p3yot3** [comment]
Sorted. Thanks domob!
